export const SITE = {
  name: 'Digital Hujra',
  tagline: 'Bringing KP Business to the Digital World',
  phone: '+92 371 5868088',
  whatsapp: '923715868088',
  email: 'info@digitalhujra.com',
  address: 'Popular Shopping Mall Plaza, Near Gul Rang Khadi Hall, Amandara Batkhela, KP',
  addressShort: 'Amandara Batkhela, KP',
  instagram: '',
  facebook: '',
  tiktok: '',
  youtube: '',
} as const

export const STATS = [
  { value: 6,   suffix: '',  label: 'Services Offered',  sub: 'POS · Software · E-Commerce · Photography · WhatsApp · Google',  v: '6',    l: 'Services Offered' },
  { value: 5,   suffix: '+', label: 'Cities in KP',      sub: 'Batkhela · Swat · Dir · Mardan · Peshawar', v: '5+',   l: 'Cities in KP'     },
  { value: 48,  suffix: 'h', label: 'Avg. Delivery',     sub: 'Fast turnaround on every project',          v: '48h',  l: 'Avg. Delivery'    },
  { value: 100, suffix: '%', label: 'Satisfaction',       sub: "We don't stop until you're happy",          v: '100%', l: 'Satisfaction'     },
]

export const TEAM = [
  { initials: 'OG', name: 'Osama Ghaffar', role: 'Founder & CEO',           bio: 'Software engineer with 5+ years of experience and permanent employee at Precision Data Strategies LLC, California, USA. Founded Digital Hujra to bring world-class digital services to his hometown in KP.',  since: '2026', color: '#F5A33A', image: '/team/Osama.webp',    website: 'https://osamaghaffar.pro', linkedin: 'https://www.linkedin.com/in/osama-ghaffar423' },
  { initials: 'HB', name: 'Haseeb Ullah',  role: 'Lead Designer',           bio: 'Expert in brand identity, logo design, and visual communication for KP businesses.',    since: '2026', color: '#5BD68A', image: '/team/Haseeb.webp',    linkedin: 'https://www.linkedin.com/in/haseebullahdesigns/',          website: 'https://haseebullahdesigns.com'  },
  { initials: 'MZ', name: 'Muzamil',       role: 'Social Media Expert',     bio: 'Manages social media presence, content strategy, and audience engagement for Digital Hujra clients across KP.',  since: '2026', color: '#4FB3FF', image: '/team/Muzammil.webp',  linkedin: 'https://www.linkedin.com/in/muzamil-ghaffar-8602a8313/', website: 'https://muzamilghaffar.pro/'     },
]

export const PORTFOLIO = [
  {
    id: 'classyfitters',
    client: 'Classyfitters',
    service: 'E-commerce · Product Shoot · WhatsApp Business · Google Business',
    location: 'Batkhela, KP',
    tagline: 'Full digital launch — online store, product shoot, WhatsApp & Google Business setup',
    coverEmoji: '👗',
    coverImage: '',
    featured: true,
  },
  {
    id: 'raazina-essence',
    client: 'Raazina Essence',
    service: 'Product Photography',
    location: 'Shamozo, Swat, KP',
    tagline: '50+ perfume product shots across two studio shoot sessions',
    coverEmoji: '🌙',
    coverImage: '',
    featured: false,
  },
  {
    id: 'al-ansar-abaya',
    client: 'Al Ansar Abaya',
    service: 'E-Commerce · Photography · WhatsApp · Google Business',
    location: 'Chakdara, KP',
    tagline: 'Complete digital presence — store, shoot, WhatsApp verified & Google Business',
    coverEmoji: '🤍',
    coverImage: '',
    featured: false,
  },
  {
    id: 'bayan-cafe',
    client: 'Bayan Cafe',
    service: 'Design & Print',
    location: 'Batkhela, KP',
    tagline: 'Logo, color system, typography, brand guidelines, and print collateral — all delivered',
    coverEmoji: '☕',
    coverImage: '',
    featured: false,
  },
]

export const TESTIMONIALS = [
  {
    id: 'raazina',
    client: 'Raazina Essence',
    business: 'Raazina Essence',
    location: 'Shamozo, Swat, KP',
    service: 'Product Photography',
    review: 'Digital Hujra ne hamare Raazina Ice perfume ke liye jo shoot kiya — woh hamari expectations se kahin behtar tha. Professional, fast, aur bilkul woh feel jo hum chahte the.',
    rating: 5,
    // component-compatibility aliases
    q: 'Digital Hujra ne hamare Raazina Ice perfume ke liye jo shoot kiya — woh hamari expectations se kahin behtar tha. Professional, fast, aur bilkul woh feel jo hum chahte the.',
    name: 'Raazina Essence',
    role: 'Product Photography Client',
    city: 'Swat, KP',
  },
]

export const WA_MESSAGES: Record<string, string> = {
  default:   'Assalam o Alaikum! Digital Hujra se contact kar raha hoon. Mujhe services ke baare mein baat karni thi.',
  pos:       'Assalam o Alaikum! POS system ke baare mein maloomat chahiye.',
  ecommerce: 'Assalam o Alaikum! E-commerce website banwani hai.',
  software:  'Assalam o Alaikum! Custom software ke baare mein enquire karna tha.',
  photo:     'Assalam o Alaikum! Product photography ke baare mein enquire karna tha.',
  whatsapp:  'Assalam o Alaikum! WhatsApp Business setup ke baare mein enquire karna tha.',
  google:    'Assalam o Alaikum! Google Business setup ke baare mein enquire karna tha.',
}

// ── Component-compatibility exports ──────────────────────────────────────────

export const NAV_ITEMS = [
  { l: 'Services', h: '/services'  },
  { l: 'Packages', h: '/packages' },
  { l: 'About',    h: '/about'    },
  { l: 'Team',     h: '/team'     },
  { l: 'Contact',  h: '/contact'  },
]

export const SERVICES = [
  { n: '01', name: 'POS Systems',     icon: 'pos',    accent: 'amber', blurb: 'Modern point-of-sale for pharmacies, marts, and restaurants — installed, configured, and staff-trained.',        bullets: ['Inventory tracking', 'Daily Z-reports', 'Urdu/Pashto receipts', 'Works offline', 'Staff training', 'Remote support'] },
  { n: '02', name: 'Custom Software', icon: 'code',   accent: 'amber', blurb: 'Inventory systems, billing apps, booking platforms, and internal tools — built to match how your business actually works.', bullets: ['Desktop & web apps', 'Inventory & billing', 'Booking & CRM tools', 'Urdu / Pashto UI', 'Training included', 'Annual support'] },
  { n: '03', name: 'E-Commerce',      icon: 'cart',   accent: 'blue',  blurb: 'Online shops with Cash on Delivery, WhatsApp checkout, and local courier integrations — ready in weeks.',          bullets: ['Cash on Delivery', 'WhatsApp checkout', 'Courier integration', 'Bilingual UI'] },
  { n: '04', name: 'Photography',      icon: 'camera',   accent: 'blue',  blurb: 'Studio and on-location shoots with 48-hour delivery. Catalog-ready cutouts and lifestyle scenes.',                                                                                                             bullets: ['Studio shoots', 'On-location', 'Product cutouts', '48h turnaround'] },
  { n: '05', name: 'WhatsApp Business', icon: 'whatsapp', accent: 'green', blurb: 'WhatsApp Business profile, verified green tick, channel setup, and catalog — turn WhatsApp into your primary sales and support channel.',                                                                              bullets: ['Business profile setup', 'Green tick verification', 'WhatsApp Channel', 'Product catalog', 'Auto-replies', 'Broadcast lists'] },
  { n: '06', name: 'Google Business',   icon: 'google',   accent: 'blue',  blurb: 'Google Business Profile creation, optimization, and local SEO so customers find, call, and visit your shop directly from Google Search and Maps.', bullets: ['Maps listing', 'Profile optimization', 'Photo uploads', 'Local SEO setup', 'Review management', 'Monthly reports'] },
]

export const WORK = [
  { id: 1, slug: 'raazina-essence', name: 'Raazina Essence', cat: 'Product Photography',                           city: 'Swat',     swatch: 'rgba(120,60,180,0.6)', preview: '/work/raazina-essence/Raazina%20Preview%20Image.webp' },
  { id: 2, slug: 'classyfitters',   name: 'Classyfitters',   cat: 'E-Commerce · Product Shoot · WhatsApp · Google', city: 'Batkhela', swatch: 'rgba(245,163,58,0.6)', preview: '/work/classyfitters/Main%20Preview%20Image.webp' },
  { id: 3, slug: 'al-ansar-abaya',  name: 'Al Ansar Abaya',  cat: 'E-Commerce · Photography · WhatsApp · Google',  city: 'Chakdara', swatch: 'rgba(91,214,138,0.5)', preview: '/work/al-ansar-abaya/Preview%20Image%20Al%20Ansar%20Abaya.webp' },
  { id: 4, slug: 'bayan-cafe',      name: 'Bayan Cafe',      cat: 'Design & Print',                                city: 'Batkhela', swatch: 'rgba(180,120,60,0.6)', preview: '/work/bayan-cafe/Preview%20Image.webp' },
]

export const PROCESS = [
  { n: '01', t: 'Discovery',  d: 'We sit with you — in the hujra or on a call — and listen. Your business, your customers, your goals. No forms, no jargon.' },
  { n: '02', t: 'Proposal',   d: 'A fixed-price quote in plain language. Scope, timeline, and deliverables — all agreed before a single pixel is moved.' },
  { n: '03', t: 'Build',      d: 'Design, develop, shoot, or install — depending on the service. You get regular updates and can give feedback at every stage.' },
  { n: '04', t: 'Handover',   d: 'We deliver, train your team, and stay available for 90 days. You own everything — files, accounts, passwords.' },
]

export const DISTRICTS = [
  'Peshawar', 'Mardan', 'Swat', 'Malakand', 'Dir Upper', 'Dir Lower',
  'Batkhela', 'Buner', 'Shangla', 'Kohistan', 'Mansehra', 'Abbottabad',
  'Haripur', 'Nowshera', 'Charsadda', 'Kohat', 'Karak', 'Bannu',
]

export const MARQUEE_WORDS = [
  'POS Systems', 'Custom Software', 'E-Commerce', 'Photography',
  'WhatsApp Business', 'Google Business', 'Digital Hujra', 'Batkhela', 'KP Business', 'Local-first', 'Growth',
]

export const PRICING = [
  {
    id: 'pos',
    tab: 'POS Systems',
    icon: 'pos',
    accent: 'amber',
    packages: [
      {
        name: 'Starter POS',
        price: 15000,
        originalPrice: 20000,
        pricePrefix: 'Starting From',
        saleBadge: 'Launch Sale',
        period: 'one-time',
        popular: false,
        tagline: 'Small shops, kiryana stores, general stores',
        features: [
          'Fast POS billing system',
          'Barcode scanning & product search',
          'Thermal invoice printing (Urdu supported)',
          'Basic stock & inventory management',
          'Customer records',
          'Daily sales report',
          'Mobile-friendly — phone & tablet ready',
          'Offline mode + auto sync',
          '30 days free support',
          'WhatsApp support',
        ],
        notIncluded: [
          'Supplier records & dues tracking',
          'Profit & loss report',
          'Business analytics dashboard',
          'Multi-device access',
        ],
        waKey: 'pos',
      },
      {
        name: 'Business POS',
        price: 35000,
        originalPrice: 42000,
        pricePrefix: 'Starting From',
        saleBadge: 'Launch Sale',
        period: 'one-time',
        popular: true,
        tagline: 'Pharmacies, clothing stores, restaurants, marts',
        features: [
          'Everything in Starter, plus:',
          'Supplier records & dues tracking',
          'Invoice & billing management',
          'Expense management',
          'Profit & loss reporting',
          'Business analytics dashboard',
          'Area-wise customer management',
          'Up to 3 device access',
          '24/7 technical support',
          '3 months free support',
          'Staff training session included',
        ],
        notIncluded: [
          'Multi-branch / multi-location management',
          'Custom reports & data export',
          'On-site support visits',
          'Dedicated account manager',
        ],
        waKey: 'pos',
      },
      {
        name: 'Enterprise POS',
        price: 75000,
        originalPrice: 90000,
        pricePrefix: 'Starting From',
        saleBadge: 'Launch Sale',
        period: 'one-time',
        popular: false,
        tagline: 'Multi-branch businesses, wholesale distributors, supermarkets',
        features: [
          'Everything in Business, plus:',
          'Multi-branch / multi-location management',
          'Unlimited device access',
          'Role-based user access controls',
          'Custom reports & data export',
          'Advanced analytics & forecasting',
          '24/7 priority support',
          '6 months free support',
          'On-site support visits',
          'All branch staff training',
          'Dedicated account manager',
        ],
        waKey: 'pos',
      },
    ],
  },
  {
    id: 'software',
    tab: 'Custom Software',
    icon: 'code',
    accent: 'amber',
    packages: [
      {
        name: 'Small Business',
        price: 40000,
        originalPrice: 55000,
        pricePrefix: 'Starting From',
        saleBadge: 'Launch Sale',
        period: 'one-time',
        popular: false,
        tagline: 'Small schools, clinics, shops · up to 5 users',
        features: [
          'Custom-built for your business',
          'Mobile-friendly web application',
          'User login & basic permissions',
          'Data entry & record management',
          'Search & filter functionality',
          'PDF & Excel reports export',
          'Offline mode + auto sync',
          'Up to 5 user accounts',
          '30 days free support',
          'Delivery in 4–6 weeks',
        ],
        notIncluded: [
          'Analytics dashboard & charts',
          'SMS / email notifications',
          'Bulk import & export',
          'Multi-branch support',
        ],
        waKey: 'software',
      },
      {
        name: 'Medium Business',
        price: 85000,
        originalPrice: 100000,
        pricePrefix: 'Starting From',
        saleBadge: 'Launch Sale',
        period: 'one-time',
        popular: true,
        tagline: 'Schools, hospitals, HR systems, distributors · up to 25 users',
        features: [
          'Everything in Starter, plus:',
          'Analytics dashboard & charts',
          'Role-based access control',
          'Automated SMS & email notifications',
          'Bulk import & export',
          'Custom report builder',
          'Activity & audit logs',
          'Up to 25 user accounts',
          'Up to 3 branch locations',
          '90 days free support',
          '24/7 WhatsApp support',
          'Delivery in 6–10 weeks',
        ],
        notIncluded: [
          'Unlimited users & branches',
          'API & third-party integrations',
          'Custom module development',
          'Dedicated project manager',
        ],
        waKey: 'software',
      },
      {
        name: 'Large Business',
        price: 200000,
        priceDisplay: 'PKR 2,00,000+',
        originalPrice: 230000,
        originalPriceDisplay: 'PKR 2,30,000+',
        pricePrefix: 'Starting From',
        saleBadge: 'Launch Sale',
        period: 'one-time',
        popular: false,
        tagline: 'Universities, hospital networks, large ERP · unlimited users',
        features: [
          'Everything in Medium, plus:',
          'Unlimited user accounts',
          'Unlimited branch locations',
          'API & third-party integrations',
          'Custom module development',
          'Dedicated cloud server setup',
          'Automated data backup & recovery',
          '6 months free support',
          '24/7 priority support',
          'On-site support visits',
          'Dedicated project manager',
          'Delivery in 10–16 weeks',
        ],
        waKey: 'software',
      },
    ],
  },
  {
    id: 'ecommerce',
    tab: 'E-Commerce',
    icon: 'cart',
    accent: 'blue',
    sectionNote: 'Orders via WhatsApp or COD — no payment gateway. Customers pay via Cash on Delivery or send Easypaisa/JazzCash to your account number and share screenshot for confirmation. Simple and trusted by KP customers.',
    footerNote: 'All prices in PKR · 50% advance to begin · 50% on store delivery · No payment gateway integration · COD + manual bank transfer only · Custom quotes available on request',
    packages: [
      {
        name: 'Basic Store',
        price: 18000,
        period: 'one-time',
        popular: false,
        tagline: 'For small shops going online for the first time',
        pricePrefix: 'Starting From',
        features: [
          'Up to 30 products listed',
          'Mobile-first responsive design',
          'WhatsApp order button on every product',
          'Cash on Delivery setup',
          'Easypaisa / JazzCash account number display',
          'Screenshot payment confirmation system',
          'Contact & inquiry form',
          'Google Maps location embed',
          'Basic SEO setup',
          '30-day WhatsApp support',
          'Delivered in 7–10 days',
        ],
        waKey: 'ecommerce',
      },
      {
        name: 'Business Store',
        price: 32000,
        period: 'one-time',
        popular: true,
        tagline: 'For clothing brands, pharmacies & product sellers',
        pricePrefix: 'Starting From',
        features: [
          'Up to 100 products with categories',
          'Custom branded design (your logo & colors)',
          'Product search & filter',
          'Sale banners & discount display',
          'Easypaisa + JazzCash account number display',
          'Screenshot payment confirmation system',
          'WhatsApp auto-message on every order',
          'Google Analytics installed',
          'Full SEO — title, meta, sitemap',
          '90-day WhatsApp support',
          '1 staff training session included',
          'Delivered in 10–14 days',
        ],
        waKey: 'ecommerce',
      },
      {
        name: 'Full Store',
        price: 55000,
        period: 'one-time',
        popular: false,
        tagline: 'For scaling brands with full online operations',
        pricePrefix: 'Starting From',
        features: [
          'Unlimited products & categories',
          'Custom branded design (matches logo & colors)',
          'Multi-city delivery zone management',
          'Order management dashboard',
          'Customer accounts & order history',
          'Daraz / social media product sync',
          'Monthly sales analytics report',
          'POS sync (if applicable)',
          '6-month WhatsApp support',
          '2 staff training sessions',
          'Delivered in 14–21 days',
        ],
        waKey: 'ecommerce',
      },
    ],
  },
  {
    id: 'photography',
    tab: 'Photography',
    icon: 'camera',
    accent: 'amber',
    footerNote: 'All prices in PKR · 50% advance to confirm booking · balance on WhatsApp delivery of photos · Studio in Batkhela · Outdoor shoots available on request · Reshoot guarantee on Full Catalogue',
    packages: [
      {
        name: 'Mini Shoot',
        price: 9000,
        period: 'shoot',
        popular: false,
        tagline: 'For new sellers needing clean product photos fast',
        photoSubLabel: 'Up to 50 photos delivered',
        perPhotoLabel: 'PKR 180 per photo',
        paymentNote: 'Book PKR 4,500 today · PKR 4,500 on photo delivery',
        features: [
          'Up to 50 product photos',
          'White background shots',
          'Professional studio lighting',
          'Basic colour correction',
          'High-res JPG files',
          'WhatsApp delivery within 24 hours',
          'Commercial use rights included',
        ],
        waKey: 'photo',
      },
      {
        name: 'Brand Shoot',
        price: 15000,
        period: 'shoot',
        popular: true,
        tagline: 'For clothing stores, pharmacies & product sellers',
        photoSubLabel: 'Up to 100 photos delivered',
        perPhotoLabel: 'PKR 150 per photo — best value',
        paymentNote: 'Book PKR 7,500 today · PKR 7,500 on photo delivery',
        features: [
          'Up to 100 product photos',
          'White background + lifestyle + flat-lay styles',
          'Multiple angles per product',
          'Full retouching & colour grading',
          'High-res + web-optimised files both',
          'Instagram square crops ready',
          'Dedicated 3-hour studio session',
          'WhatsApp delivery within 48 hours',
          'Commercial use rights included',
        ],
        waKey: 'photo',
      },
      {
        name: 'Full Catalogue',
        price: 22000,
        period: 'shoot',
        popular: false,
        tagline: 'For large stores & wholesalers — complete inventory coverage',
        photoSubLabel: '150+ photos delivered',
        perPhotoLabel: 'PKR 146 per photo — maximum saving',
        paymentNote: 'Book PKR 11,000 today · PKR 11,000 on photo delivery',
        features: [
          '150+ product photos',
          'All styles: white, lifestyle, flat-lay, on-model',
          'Full professional retouching',
          'High-res + web + social media sizes',
          'Instagram carousel sets prepared',
          'E-commerce ready — formatted for Daraz, website & WhatsApp',
          'Full-day dedicated studio session',
          'WhatsApp delivery within 72 hours',
          '1 free reshoot if not satisfied',
          'Commercial use rights included',
        ],
        waKey: 'photo',
      },
    ],
  },
  {
    id: 'whatsapp',
    tab: 'WhatsApp Business',
    icon: 'whatsapp',
    accent: 'green',
    packages: [
      {
        name: 'Basic Setup',
        price: 2500,
        pricePrefix: 'Starting From',
        saleBadge: 'Launch Sale',
        period: 'one-time',
        popular: false,
        tagline: 'Any shop needing a professional WhatsApp presence',
        features: [
          'WhatsApp Business profile setup',
          'Business name, description & address',
          'Business hours configuration',
          'Quick replies & greeting message',
          'Away message setup',
          'Product/service catalog (up to 20 items)',
          'WhatsApp QR code & link generation',
          '30-day WhatsApp support',
        ],
        notIncluded: [
          'WhatsApp Green Tick verification',
          'WhatsApp Channel creation',
          'Broadcast list configuration',
          'Multi-agent inbox setup',
        ],
        waKey: 'whatsapp',
      },
      {
        name: 'Business + Verified',
        price: 6500,
        pricePrefix: 'Starting From',
        saleBadge: 'Launch Sale',
        period: 'one-time',
        popular: true,
        tagline: 'Established shops wanting credibility and reach',
        features: [
          'Everything in Basic, plus:',
          'WhatsApp Verified Green Tick (✅)',
          'WhatsApp Channel creation & branding',
          'Custom business profile cover',
          'Label & contact organization',
          'Broadcast list configuration',
          'Auto-reply flows for common questions',
          '90-day WhatsApp support',
        ],
        notIncluded: [
          'WhatsApp Business API connection',
          'Multi-agent inbox (3+ staff)',
          'Custom order automation flows',
        ],
        waKey: 'whatsapp',
      },
      {
        name: 'Full WhatsApp Suite',
        price: 11000,
        pricePrefix: 'Starting From',
        saleBadge: 'Launch Sale',
        period: 'one-time',
        popular: false,
        tagline: 'Brands ready to use WhatsApp as a full sales channel',
        features: [
          'Everything in Business + Verified, plus:',
          'WhatsApp Business API connection',
          'Custom order & enquiry automation',
          'Multi-agent inbox (up to 3 staff)',
          'Expanded catalog (100+ products)',
          'Analytics & message tracking setup',
          'Staff training session included',
          '6-month WhatsApp support',
        ],
        waKey: 'whatsapp',
      },
    ],
  },
  {
    id: 'google',
    tab: 'Google Business',
    icon: 'google',
    accent: 'blue',
    packages: [
      {
        name: 'Basic Listing',
        price: 2000,
        pricePrefix: 'Starting From',
        saleBadge: 'Launch Sale',
        period: 'one-time',
        popular: false,
        tagline: 'Any local shop that needs to appear on Google Maps',
        features: [
          'Google Business Profile creation',
          'Business name, address & phone',
          'Category & description setup',
          'Google Maps pin placement',
          '10 business photos uploaded',
          'Opening hours configuration',
          'Basic Q&A setup',
          '30-day support',
        ],
        notIncluded: [
          'Keyword-optimized description',
          'Competitor keyword research',
          'Google Posts setup',
          'Citation & directory building',
        ],
        waKey: 'google',
      },
      {
        name: 'Optimized Profile',
        price: 4500,
        pricePrefix: 'Starting From',
        saleBadge: 'Launch Sale',
        period: 'one-time',
        popular: true,
        tagline: 'Shops wanting to rank higher in local searches',
        features: [
          'Everything in Basic, plus:',
          'Keyword-optimized business description',
          '30+ branded photos uploaded',
          'Service areas fully configured',
          'Review response templates',
          'Google Posts setup (5 posts)',
          'WhatsApp & website link integration',
          '90-day support',
        ],
        notIncluded: [
          'Competitor keyword research',
          'Citation & directory building',
          'Monthly performance reports',
        ],
        waKey: 'google',
      },
      {
        name: 'Full Local SEO',
        price: 8000,
        pricePrefix: 'Starting From',
        saleBadge: 'Launch Sale',
        period: 'one-time',
        popular: false,
        tagline: 'Businesses serious about dominating local search',
        features: [
          'Everything in Optimized, plus:',
          'Full competitor keyword research',
          'Google Business category optimization',
          'Citation & directory building (10 sites)',
          'Monthly Google Posts (for 3 months)',
          'Monthly performance reports (3 months)',
          'Training session for managing reviews',
          '6-month support',
        ],
        waKey: 'google',
      },
    ],
  },
]
