export const SITE = {
  name: 'Digital Hujra',
  tagline: 'Bringing KP Business to the Digital World',
  phone: '+92 371 5868088',
  whatsapp: '923715868088',
  email: 'info@digitalhujra.com',
  address: 'Popular Shopping Mall Plaza, Near Gul Rang Khadi Hall, Amandara Batkhela, KP',
  addressShort: 'Amandara Batkhela, KP',
  instagram: '',
  facebook: '',
  tiktok: '',
  youtube: '',
} as const

export const STATS = [
  { value: 6,   suffix: '+', label: 'Services Offered',  sub: 'Photography to POS — all under one roof',   v: '6+',   l: 'Services Offered' },
  { value: 5,   suffix: '+', label: 'Cities in KP',      sub: 'Batkhela · Swat · Dir · Mardan · Peshawar', v: '5+',   l: 'Cities in KP'     },
  { value: 48,  suffix: 'h', label: 'Avg. Delivery',     sub: 'Fast turnaround on every project',          v: '48h',  l: 'Avg. Delivery'    },
  { value: 100, suffix: '%', label: 'Satisfaction',       sub: "We don't stop until you're happy",          v: '100%', l: 'Satisfaction'     },
]

export const TEAM = [
  { initials: 'OG', name: 'Osama Ghaffar', role: 'Founder & CEO',           bio: 'Started Digital Hujra to bring professional digital services to local KP businesses.',  since: '2026', color: '#F5A33A', image: '/team/osama.jpg'      },
  { initials: 'DH', name: 'Co-Founder',    role: 'Co-Founder',              bio: 'Expert in software development, and leading the whole department.',                     since: '2026', color: '#2A9DF4', image: '/team/cofounder.jpg'  },
  { initials: 'HB', name: 'Haseeb',        role: 'Lead Designer',           bio: 'Expert in brand identity, logo design, and visual communication for KP businesses.',    since: '2026', color: '#5BD68A', image: '/team/haseeb.jpg'     },
  { initials: 'MZ', name: 'Muzamil',       role: 'Brand & Visual Designer', bio: 'Specializes in social media design, print materials, and digital brand assets.',       since: '2026', color: '#4FB3FF', image: '/team/muzamil.jpg'    },
]

export const PORTFOLIO = [
  {
    id: 'classyfitters',
    client: 'Classyfitters',
    service: 'Branding & Social Media',
    location: 'Batkhela, KP',
    tagline: 'Premium fashion brand identity for Classyfitters',
    coverEmoji: '👗',
    coverImage: '',
    featured: true,
  },
  {
    id: 'edenrobe-batkhela',
    client: 'Edenrobe Batkhela Amandara',
    service: 'Social Media & Photography',
    location: 'Amandara, Batkhela, KP',
    tagline: 'Digital presence for Edenrobe Batkhela franchise',
    coverEmoji: '🏪',
    coverImage: '',
    featured: false,
  },
  {
    id: 'raazina-essence',
    client: 'Raazina Essence',
    service: 'Product Photography',
    location: 'Shamozo, Swat, KP',
    tagline: '50+ premium mockup images — Raazina Ice perfume',
    coverEmoji: '🌙',
    coverImage: '',
    featured: false,
  },
  {
    id: 'al-ansar-abaya',
    client: 'Al Ansar Abaya',
    service: 'Branding & Photography',
    location: 'Chakdara, KP',
    tagline: 'Elegant brand identity for Al Ansar Abaya collection',
    coverEmoji: '🤍',
    coverImage: '',
    featured: false,
  },
]

export const TESTIMONIALS = [
  {
    id: 'raazina',
    client: 'Raazina Essence',
    business: 'Raazina Essence',
    location: 'Shamozo, Swat, KP',
    service: 'Product Photography',
    review: 'Digital Hujra ne hamare Raazina Ice perfume ke liye jo shoot kiya — woh hamari expectations se kahin behtar tha. Professional, fast, aur bilkul woh feel jo hum chahte the.',
    rating: 5,
    // component-compatibility aliases
    q: 'Digital Hujra ne hamare Raazina Ice perfume ke liye jo shoot kiya — woh hamari expectations se kahin behtar tha. Professional, fast, aur bilkul woh feel jo hum chahte the.',
    name: 'Raazina Essence',
    role: 'Product Photography Client',
    city: 'Swat, KP',
  },
]

export const WA_MESSAGES: Record<string, string> = {
  default:   'Assalam o Alaikum! Digital Hujra se contact kar raha hoon. Mujhe services ke baare mein baat karni thi.',
  pos:       'Assalam o Alaikum! POS system ke baare mein maloomat chahiye.',
  ecommerce: 'Assalam o Alaikum! E-commerce website banwani hai.',
  branding:  'Assalam o Alaikum! Brand identity ke baare mein baat karni thi.',
  social:    'Assalam o Alaikum! Social media management ke baare mein enquire karna tha.',
  photo:     'Assalam o Alaikum! Product photography ke baare mein enquire karna tha.',
  video:     'Assalam o Alaikum! Video editing ke baare mein enquire karna tha.',
  graphic:   'Assalam o Alaikum! Graphic design ke liye inquiry karna chahta hoon.',
}

// ── Component-compatibility exports ──────────────────────────────────────────

export const NAV_ITEMS = [
  { l: 'Services', h: '/services' },
  { l: 'Work',     h: '/#work'    },
  { l: 'About',    h: '/about'    },
  { l: 'Team',     h: '/team'     },
  { l: 'Contact',  h: '/contact'  },
]

export const SERVICES = [
  { n: '01', name: 'POS Systems',          icon: 'pos',    accent: 'amber', blurb: 'Modern point-of-sale for pharmacies, marts, and restaurants — installed, configured, and staff-trained.',         bullets: ['Inventory tracking', 'Daily Z-reports', 'Urdu/Pashto receipts', 'Works offline', 'Staff training', 'Remote support'] },
  { n: '02', name: 'E-commerce Stores',    icon: 'cart',   accent: 'blue',  blurb: 'Online shops with Cash on Delivery, WhatsApp checkout, and local courier integrations — ready in weeks.',            bullets: ['Cash on Delivery', 'WhatsApp checkout', 'Courier integration', 'Bilingual UI'] },
  { n: '03', name: 'Branding & Identity',  icon: 'brand',  accent: 'amber', blurb: 'Logo, color system, typography, and brand book — identities that hold together across print and screen.',            bullets: ['Logo + variants', 'Color & type system', 'Stationery', 'Brand guidelines'] },
  { n: '04', name: 'Social Media',         icon: 'social', accent: 'blue',  blurb: 'Monthly content calendars, Reels, Stories, and targeted Meta ads — with plain-language performance reports.',        bullets: ['Content calendar', 'Reels & Stories', 'Meta & TikTok ads', 'Monthly report'] },
  { n: '05', name: 'Product Photography',  icon: 'camera', accent: 'amber', blurb: 'Studio and on-location shoots with 48-hour delivery. Catalog-ready cutouts and lifestyle scenes.',                  bullets: ['Studio shoots', 'On-location', 'Product cutouts', '48h turnaround'] },
  { n: '06', name: 'Video Editing',        icon: 'video',  accent: 'blue',  blurb: 'Reels, brand films, ad cuts, and explainers — color graded, captioned, and delivered to your phone.',               bullets: ['Short-form Reels', 'Brand films', 'Ad cuts', 'Motion graphics'] },
  { n: '07', name: 'Graphic Design',       icon: 'grid',   accent: 'amber', blurb: 'Menus, packaging, banners, and signage — all in print-ready formats, sent to your local press.',                   bullets: ['Menus & print', 'Packaging', 'Banners & signage', 'Print-ready files'] },
]

export const WORK = [
  { id: 1, name: 'Classyfitters',            cat: 'Branding & Social Media',    city: 'Batkhela',  swatch: 'rgba(245,163,58,0.6)'  },
  { id: 2, name: 'Edenrobe Batkhela',        cat: 'Social Media & Photography', city: 'Amandara',  swatch: 'rgba(42,157,244,0.5)'  },
  { id: 3, name: 'Raazina Essence',          cat: 'Product Photography',        city: 'Swat',      swatch: 'rgba(120,60,180,0.6)'  },
  { id: 4, name: 'Al Ansar Abaya',           cat: 'Branding & Photography',     city: 'Chakdara',  swatch: 'rgba(91,214,138,0.5)'  },
]

export const PROCESS = [
  { n: '01', t: 'Discovery',  d: 'We sit with you — in the hujra or on a call — and listen. Your business, your customers, your goals. No forms, no jargon.' },
  { n: '02', t: 'Proposal',   d: 'A fixed-price quote in plain language. Scope, timeline, and deliverables — all agreed before a single pixel is moved.' },
  { n: '03', t: 'Build',      d: 'Design, develop, shoot, or install — depending on the service. You get regular updates and can give feedback at every stage.' },
  { n: '04', t: 'Handover',   d: 'We deliver, train your team, and stay available for 90 days. You own everything — files, accounts, passwords.' },
]

export const DISTRICTS = [
  'Peshawar', 'Mardan', 'Swat', 'Malakand', 'Dir Upper', 'Dir Lower',
  'Batkhela', 'Buner', 'Shangla', 'Kohistan', 'Mansehra', 'Abbottabad',
  'Haripur', 'Nowshera', 'Charsadda', 'Kohat', 'Karak', 'Bannu',
]

export const MARQUEE_WORDS = [
  'POS Systems', 'E-commerce', 'Branding', 'Social Media',
  'Photography', 'Video Editing', 'Graphic Design', 'Digital Hujra',
  'Batkhela', 'KP Business', 'Local-first', 'Growth',
]

export const PRICING = [
  {
    id: 'pos',
    tab: 'POS Systems',
    icon: 'pos',
    accent: 'amber',
    packages: [
      {
        name: 'Basic',
        price: 18000,
        period: 'one-time',
        popular: false,
        tagline: 'For small kiosks & single shops',
        features: [
          '1 POS terminal setup',
          'Basic inventory tracking',
          'Daily Z-reports',
          'Urdu/Pashto receipts',
          'Staff training (1 session)',
          '30-day support',
        ],
        waKey: 'pos',
      },
      {
        name: 'Business',
        price: 38000,
        period: 'one-time',
        popular: true,
        tagline: 'For growing pharmacies & marts',
        features: [
          '2 POS terminals setup',
          'Full inventory & stock alerts',
          'Daily Z-reports + monthly summary',
          'Barcode scanner integration',
          'Staff training (2 sessions)',
          '90-day remote support',
        ],
        waKey: 'pos',
      },
      {
        name: 'Multi-Branch',
        price: 72000,
        period: 'one-time',
        popular: false,
        tagline: 'For chains & multi-outlet businesses',
        features: [
          'Unlimited terminals',
          'Central inventory dashboard',
          'Branch-wise reporting',
          'Customer loyalty module',
          'Unlimited staff training',
          'Annual remote support contract',
        ],
        waKey: 'pos',
      },
    ],
  },
  {
    id: 'ecommerce',
    tab: 'E-commerce',
    icon: 'cart',
    accent: 'blue',
    packages: [
      {
        name: 'Starter Store',
        price: 28000,
        period: 'one-time',
        popular: false,
        tagline: 'Launch your first online shop',
        features: [
          'Up to 50 products',
          'Cash on Delivery integration',
          'WhatsApp checkout button',
          'Mobile-optimised design',
          'Basic SEO setup',
          '30-day support',
        ],
        waKey: 'ecommerce',
      },
      {
        name: 'Growth Store',
        price: 58000,
        period: 'one-time',
        popular: true,
        tagline: 'Scale with full e-commerce power',
        features: [
          'Unlimited products',
          'COD + courier integrations',
          'Bilingual UI (Urdu + English)',
          'Advanced product filters',
          'Email & WhatsApp order alerts',
          'Google Analytics setup',
          '90-day support',
        ],
        waKey: 'ecommerce',
      },
      {
        name: 'Custom Platform',
        price: 105000,
        period: 'one-time',
        popular: false,
        tagline: 'Enterprise-grade, built to scale',
        features: [
          'Custom UI/UX design',
          'Multi-vendor option',
          'API integrations (couriers, payment)',
          'Admin panel + analytics',
          'Speed & conversion optimisation',
          '6-month priority support',
        ],
        waKey: 'ecommerce',
      },
    ],
  },
  {
    id: 'branding',
    tab: 'Branding',
    icon: 'brand',
    accent: 'amber',
    packages: [
      {
        name: 'Essential',
        price: 12000,
        period: 'one-time',
        popular: false,
        tagline: 'A mark that sets you apart',
        features: [
          'Logo + 2 variants',
          'Primary color palette',
          'Font selection',
          'PNG, SVG, PDF files',
          '2 revision rounds',
        ],
        waKey: 'branding',
      },
      {
        name: 'Identity Kit',
        price: 28000,
        period: 'one-time',
        popular: true,
        tagline: 'Full identity across every touchpoint',
        features: [
          'Logo system (primary + sub-marks)',
          'Full color & typography system',
          'Business card + letterhead',
          'Brand guidelines PDF',
          'Social media profile templates',
          '4 revision rounds',
        ],
        waKey: 'branding',
      },
      {
        name: 'Brand Launch',
        price: 52000,
        period: 'one-time',
        popular: false,
        tagline: 'Launch-ready brand from day one',
        features: [
          'Complete identity kit (all above)',
          'Packaging & label design',
          'Shop signage design',
          '10 social media templates',
          'Brand launch Reel + story',
          'Unlimited revisions',
        ],
        waKey: 'branding',
      },
    ],
  },
  {
    id: 'social',
    tab: 'Social Media',
    icon: 'social',
    accent: 'blue',
    packages: [
      {
        name: 'Starter',
        price: 18000,
        period: 'month',
        popular: false,
        tagline: 'Stay consistent and get noticed',
        features: [
          '12 designed posts / month',
          '2 platforms (FB + IG)',
          'Caption & hashtag writing',
          'Monthly content calendar',
          'Basic performance report',
        ],
        waKey: 'social',
      },
      {
        name: 'Growth',
        price: 35000,
        period: 'month',
        popular: true,
        tagline: 'Content + ads that drive real sales',
        features: [
          '24 posts + 4 Reels / month',
          '3 platforms (FB, IG, TikTok)',
          'Meta & TikTok ads management',
          'Ad budget up to PKR 10,000',
          'Weekly analytics report',
          'Competitor monitoring',
        ],
        waKey: 'social',
      },
      {
        name: 'Agency',
        price: 65000,
        period: 'month',
        popular: false,
        tagline: 'Full-service brand growth partner',
        features: [
          'Daily content (30+ posts)',
          '8 Reels + 2 brand films / month',
          'All platforms + WhatsApp broadcast',
          'Full ads strategy & management',
          'Monthly strategy call',
          'Dedicated account manager',
        ],
        waKey: 'social',
      },
    ],
  },
  {
    id: 'photography',
    tab: 'Photography',
    icon: 'camera',
    accent: 'amber',
    packages: [
      {
        name: 'Essentials',
        price: 9000,
        period: 'shoot',
        popular: false,
        tagline: 'Clean product shots delivered fast',
        features: [
          'Half-day session (3 hrs)',
          '20 edited images',
          '1 product setup / backdrop',
          'White-background cutouts',
          '48h delivery',
        ],
        waKey: 'photo',
      },
      {
        name: 'Studio Pro',
        price: 20000,
        period: 'shoot',
        popular: true,
        tagline: 'Full-day, multi-setup shoot',
        features: [
          'Full-day session (7 hrs)',
          '60 edited images',
          'Multiple setups & backdrops',
          'Product cutouts + lifestyle shots',
          'Behind-the-scenes Reel',
          '48h delivery',
        ],
        waKey: 'photo',
      },
      {
        name: 'Campaign',
        price: 38000,
        period: 'shoot',
        popular: false,
        tagline: 'Campaign-grade visuals, 2 days',
        features: [
          '2-day shoot session',
          '100+ edited images',
          'On-location + studio setups',
          'Model / lifestyle photography',
          'Product cutouts + mockups',
          '2 Reels from shoot footage',
          '72h delivery',
        ],
        waKey: 'photo',
      },
    ],
  },
  {
    id: 'video',
    tab: 'Video & Graphics',
    icon: 'video',
    accent: 'blue',
    packages: [
      {
        name: 'Reels Pack',
        price: 15000,
        period: 'month',
        popular: false,
        tagline: 'Short-form video that stops the scroll',
        features: [
          '4 Reels / month',
          'Captions & text overlays',
          'Background music (licensed)',
          'Square + vertical formats',
          '5-day delivery per Reel',
        ],
        waKey: 'video',
      },
      {
        name: 'Brand Film',
        price: 32000,
        period: 'one-time',
        popular: true,
        tagline: 'Your story, professionally told',
        features: [
          '1–3 min brand video',
          'On-location + studio filming',
          'Professional colour grade',
          'Subtitles (Urdu + English)',
          'Music & sound design',
          '2 cut-down social versions',
        ],
        waKey: 'video',
      },
      {
        name: 'Monthly Bundle',
        price: 48000,
        period: 'month',
        popular: false,
        tagline: 'Video + graphics, all in one',
        features: [
          '4 Reels + 1 brand film / month',
          '15 graphic designs / month',
          'Captions, music, colour grade',
          'Print-ready files included',
          'Priority 48h turnaround',
          'Dedicated creative director',
        ],
        waKey: 'graphic',
      },
    ],
  },
]
